# Generated by Django 4.1 on 2022-09-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availme_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='lattitude',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='board',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('BLACKLISTED', 'BLACKLISTED'), ('OBJECTION', 'OBJECTION')], default='OBJECTION', max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
